name: Publish-Hugo

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).

    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1
      with:
        go-version: '1.22'
    
    - name: Install Hugo
      run: go install github.com/gohugoio/hugo@latest

    - name: Install Hugo modules
      run: hugo mod get -u

    - name: Build
      run: hugo --baseURL https://blog.okab3.com

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4